name: Behave Tests

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave
          pip install selenium

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget curl unzip
          curl -sS https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o google-chrome.deb
          sudo dpkg -i google-chrome.deb
          sudo apt-get install -f  # To fix dependencies
          wget https://chromedriver.storage.googleapis.com/135.0.7049.85/chromedriver_linux64.zip -P /tmp
          unzip /tmp/chromedriver_linux64.zip -d /usr/local/bin

      - name: Run Behave tests
        run: behave features/
