name: GitHub CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: List files for debugging
        run: ls -la
          
      - name: Verify package.json presence
        run: test -f package.json || { echo "package.json not found"; exit 1; }

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
